language: bash
services: docker

#environment php
env:
  - VARIANT=php5.6/apache
  - VARIANT=php5.6/fpm
  - VARIANT=php5.6/fpm-alpine
  - VARIANT=php5.6/cli
  - VARIANT=php7.0/apache
  - VARIANT=php7.0/fpm
  - VARIANT=php7.0/fpm-alpine
  - VARIANT=php7.0/cli
  - VARIANT=php7.1/apache
  - VARIANT=php7.1/fpm
  - VARIANT=php7.1/fpm-alpine
  - VARIANT=php7.1/cli
  - VARIANT=php7.2/apache
  - VARIANT=php7.2/fpm
  - VARIANT=php7.2/fpm-alpine
  - VARIANT=php7.2/cli

#install library from git
install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

#this script run before run system
before_script:
  - env | sort
  - wget -qO- 'https://github.com/tianon/pgp-happy-eyeballs/raw/master/hack-my-builds.sh' | bash
  - cd "$VARIANT"
  - slash='/'; image="wordpress:${VARIANT//$slash/-}"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build -t "$image" .
      ~/official-images/test/run.sh "$image"
    )

#this script run after system run
after_script:
  - docker images

# vim:set et ts=2 sw=2:
